config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  # sessions
  get "/sign-in", to: "sessions#new", as: "sign_in"
  post "/sign-in", to: "sessions#create"
  post "/sign-out", to: "sessions#destroy", as: "sign_out"

  # users
  get "/sign-up", to: "users#new", as: "sign_up"
  post "/sign-up", to: "users#create"
  get "/dashboard", to: "users#show", as: "dashboard"
  get "/invite/:token", to: "users#reset", as: "membership_invite"
  get "/reset/:token", to: "users#reset", as: "reset_password"
  get "/forgot-your-password", to: "users#forgot", as: "forgot_password"
  post "/reset", to: "users#send_reset", as: "send_reset"
  get "/reset-sent", to: "users#reset_sent", as: "reset_sent"
  get "/assign-email/:id", to: "users#assign_email", as: "assign_email"
  patch "/set-email/:id", to: "users#set_email", as: "set_email"

  resources :users, only: [:update]

  resources :leagues, only: [:new, :create, :show, :edit, :update, :destroy] do
    # league::memberships
    resources :memberships, only: [:index, :new, :create, :edit, :update, :destroy]
    patch "/membership/:id/reactivate/", to: "memberships#reactivate", as: "membership_reactivate"

    # league::games
    resources :games, only: [:new, :create]
  end

  # games
  resources :games, only: [:show]
end

app/models/membership.rb
class Membership < ApplicationRecord
  acts_as_paranoid column: :deactivated_at

  belongs_to :league
  belongs_to :user
  accepts_nested_attributes_for :user

  delegate :email, to: :user, prefix: true

  def user_has_no_email?
    user.email.blank?
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :load_league

  def index
    @memberships = @league.memberships.with_deleted.includes(:user).decorate.group_by(&:role)
  end

  def new
    @membership = @league.memberships.new
    authorize @membership
  end

  def create
    @membership = @league.memberships.new(membership_params)
    authorize @membership
    set_user_password
    if @membership.save
      UserMailer.welcome(@membership).deliver_now if @membership.user_email && params[:notify]
      flash[:notice] = "User invited!"
      redirect_to @league
    else
      flash[:alert] = @membership.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @membership = Membership.find(params[:id]).decorate
    authorize @membership
  end

  def update
    @membership = Membership.find(params[:id])
    if @membership.update(membership_params)
      flash[:notice] = "Membership updated!"
      redirect_to league_memberships_path(@league)
    else
      flash[:alert] = @membership.errors.full_messages.join(", ")
      render :edit
    end
  end

  def destroy
    @membership = Membership.find(params[:id])
    authorize @membership
    @membership.destroy
    redirect_to league_memberships_path(@league)
  end

  def reactivate
    @membership = Membership.with_deleted.find(params[:id])
    authorize @membership
    @membership.restore
    redirect_to league_memberships_path(@league)
  end

  private

  def set_user_password
    @membership.user.password = SecureRandom.hex(13)
  end

  def load_league
    @league ||= League.find(params[:league_id])
  end

  def membership_params
    params.require(:membership).permit(
      :league_id,
      :user_id,
      :role,
      :active,
      user_attributes: [
        :email,
        :first_name,
        :last_name,
        :password
      ]
    )
  end
end

app/views/memberships/_membership_link.html.erb
<li>
  <%= membership.status_string %><%= membership.user_full_name %> - <%= membership.role_string %>
  <% if policy(membership).destroy? %>
    <% if membership.deactivated_at?%>
      <%= button_to "Reactivate", league_membership_reactivate_path(@league, membership), method: :patch %>
    <% else %>
      <%= link_to "Edit", edit_league_membership_path(@league, membership) %>
      <%= button_to "Deactivate", league_membership_path(@league, membership), method: :delete %>
    <% end %>
    <% if membership.user_has_no_email? %>
      <%= link_to "Assign email address", assign_email_path(membership.user, membership_id: membership.id) %>
    <% end %>
  <% end %>
</li>

app/views/memberships/edit.html.erb
<h2>Edit Membership for <%= @membership.user_full_name %></h2>

<%= form_with model: @membership, url: league_membership_path(@league, @membership) do |f| %>
  <%= f.label :role do %>
    <%= f.check_box :role, checked: @membership.role == 1 %>
    Admin
  <% end %>
  <%= f.submit %>
<% end %>

app/views/memberships/index.html.erb
<h1>Members of <%= link_to @league.name, league_path(@league) %></h1>
<div>
  <%= link_to "Invite new member", new_league_membership_path(@league) %>
</div>
<div>
  <h2>Admin</h2>
  <ul>
    <%= render partial: "membership_link", collection: @memberships[1], as: :membership %>
  </ul>
</div>

<div>
  <h2>Members</h2>
  <ul>
    <%= render partial: "membership_link", collection: @memberships[0], as: :membership %>
  </ul>
</div>

app/views/memberships/new.html.erb
<h2>Invite a new player to <%= link_to @league.name, league_path(@league) %></h2>

<%= form_with model: @membership, url: league_memberships_path do |f| %>
  <%= f.fields_for :user, User.new do |ff| %>
    <div>
      <%= ff.label :email, "Email (optional)" %>
      <%= ff.text_field :email %>
    </div>
    <div>
      <%= ff.label :first_name %>
      <%= ff.text_field :first_name %>
    </div>
    <div>
      <%= ff.label :last_name %>
      <%= ff.text_field :last_name %>
    </div>
    <div>
      <%= label_tag do %>
        <%= check_box_tag :notify %>
        Notify user (requires email address)
      <% end %>
    </div>
  <% end %>
  <div>
    <%= f.label :role do%>
      <%= f.check_box :role, checked: @membership.role == 1 %>
      Admin
    <% end %>
  </div>
  <%= f.submit "Invite User" %>
<% end %>