config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  # sessions
  get "/sign-in", to: "sessions#new", as: "sign_in"
  post "/sign-in", to: "sessions#create"
  post "/sign-out", to: "sessions#destroy", as: "sign_out"

  # users
  get "/sign-up", to: "users#new", as: "sign_up"
  post "/sign-up", to: "users#create"
  get "/dashboard", to: "users#show", as: "dashboard"
  get "/invite/:token", to: "users#reset", as: "membership_invite"
  get "/reset/:token", to: "users#reset", as: "reset_password"
  get "/forgot-your-password", to: "users#forgot", as: "forgot_password"
  post "/reset", to: "users#send_reset", as: "send_reset"
  get "/reset-sent", to: "users#reset_sent", as: "reset_sent"
  get "/assign-email/:id", to: "users#assign_email", as: "assign_email"
  patch "/set-email/:id", to: "users#set_email", as: "set_email"

  resources :users, only: [:update]

  resources :leagues, only: [:new, :create, :show, :edit, :update, :destroy] do
    # league::memberships
    resources :memberships, only: [:index, :new, :create, :edit, :update, :destroy]
    patch "/membership/:id/reactivate/", to: "memberships#reactivate", as: "membership_reactivate"

    # league::games
    resources :games, only: [:new, :create]
  end

  # games
  resources :games, only: [:show]
end

app/models/league.rb
class League < ApplicationRecord
  acts_as_paranoid

  validates :name, uniqueness: true, presence: true

  has_many :memberships do
    def members
      where("memberships.role = ?", 0)
    end

    def admin
      where("memberships.role = ?", 1)
    end
  end
  has_many :users, through: :memberships do
    def members
      where("memberships.role = ?", 0)
    end

    def admin
      where("memberships.role = ?", 1)
    end
  end
  has_many :seasons, dependent: :destroy
  has_many :season_games, through: :seasons, source: :games
  has_many :games, dependent: :destroy

  delegate :count, to: :seasons, prefix: true
  delegate :count, to: :memberships, prefix: true

  after_commit :create_active_season

  def active_season
    seasons.find_by(active: true) || create_active_season
  end

  def create_active_season
    seasons.create(active: true)
  end

  def next_game
    season_games.or(games)
      .where(completed: false, date: DateTime.now..)
      .order(date: :asc)
      .limit(1)
      .first
  end
end

app/controllers/leagues_controller.rb
require "./lib/league_creator"
require "./lib/league_destroyer"

class LeaguesController < ApplicationController
  def show
    @league = League.includes(:seasons, memberships: :user, seasons: :games).find(params[:id]).decorate
    authorize @league
  end

  def new
    @league = League.new
  end

  def create
    league_creator = LeagueCreator.new(league_params, current_user)
    if league_creator.save
      flash[:notice] = "League created!"
      redirect_to league_creator.league
    else
      flash[:alert] = league_creator.errors.join(", ")
      render :new
    end
  end

  def edit
    @league = League.find(params[:id])
    authorize @league
  end

  def update
    @league = League.find(params[:id])
    authorize @league
    if @league.update(league_params)
      flash[:notice] = "League updated!"
      redirect_to @league
    else
      flash[:alert] = @league.errors.full_messages.join(", ")
      render :edit
    end
  end

  def destroy
    @league = League.includes(:memberships).find(params[:id])
    authorize @league
    LeagueDestroyer.destroy(@league, current_user.id)
    redirect_to dashboard_path
  end

  private

  def league_params
    params.require(:league).permit(:name, :location, :private_league)
  end
end

app/views/leagues/_league_form.html.erb
<%= form_with model: @league do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
  <div>
    <%= f.label :private_league do %>
      <%= f.check_box :private_league %>
      Private League
    <% end %>
  </div>
  <%= f.submit "Save League" %>
<% end %>

app/views/leagues/edit.html.erb
<h2>Edit league</h2>
<%= render "league_form" %>

app/views/leagues/new.html.erb
<%= form_with model: @league do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
  <div>
    <%= f.label :private_league %>
    <%= f.check_box :private_league %>
  </div>
  <%= f.submit "Save League" %>

<% end %>

app/views/leagues/show.html.erb
<div class="row">
  <% if policy(@league).edit? %>
    <div class="twelve columns league-buttons">
      <%= link_to "Edit League", edit_league_path, class: "button button-primary league-button" %>
      <%= link_to "Invite new player", new_league_membership_path(@league), class: "button button-primary league-button" %>
      <%= button_to "Delete League", league_path(@league), method: :delete, class: "league-button" %>
      <%= link_to "Schedule Game", new_league_game_path(@league), class: "button button-primary" %>
    </div>

  <% end %>
</div>
<h1><%= @league.name %></h1>
<hr>
<div>
  <p>Random bits of info about the league</p>
  <div>Location: <%= @league.location %></div>
  <div>Next scheduled game: <%= @league.next_scheduled_game %></div>
</div>
<hr>
<div class="row">
  <div class="season-games six columns">
    <h2>Season Games</h2>
    <% @league.season_games.each do |game| %>
      <li><%= link_to game.date, game %></li>
    <% end %>
    <h2>Non-season Games</h2>
    <% @league.games.each do |game| %>
      <li><%= link_to game.date, game %></li>
    <% end %>
  </div>
  <div class="seasons-list six columns">
    <h3>Seasons: <%= @league.seasons_count %></h3>
    <table class="u-full-width">
      <thead>
        <tr>
          <th>#</th>
          <th>Winner / Current Leader</th>
          <th>Start Date</th>
          <th>End Date</th>
          <th># of Games</th>
        </tr>
      </thead>
      <tbody>
        <% @league.seasons.decorate.each.with_index(1) do |season, index| %>
        <tr>
          <td><%= index %></td>
          <td><%= season.winner %></td>
          <td><%= season.start_date %></td>
          <td><%= season.end_date %></td>
          <td><%= season.games_count %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div>
  <%= link_to "Members: #{@league.memberships_count}", league_memberships_path(@league) %>
</div>