config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  # sessions
  get "/sign-in", to: "sessions#new", as: "sign_in"
  post "/sign-in", to: "sessions#create"
  post "/sign-out", to: "sessions#destroy", as: "sign_out"

  # users
  get "/sign-up", to: "users#new", as: "sign_up"
  post "/sign-up", to: "users#create"
  get "/dashboard", to: "users#show", as: "dashboard"
  get "/invite/:token", to: "users#reset", as: "membership_invite"
  get "/reset/:token", to: "users#reset", as: "reset_password"
  get "/forgot-your-password", to: "users#forgot", as: "forgot_password"
  post "/reset", to: "users#send_reset", as: "send_reset"
  get "/reset-sent", to: "users#reset_sent", as: "reset_sent"
  get "/assign-email/:id", to: "users#assign_email", as: "assign_email"
  patch "/set-email/:id", to: "users#set_email", as: "set_email"

  resources :users, only: [:update]

  resources :leagues, only: [:new, :create, :show, :edit, :update, :destroy] do
    # league::memberships
    resources :memberships, only: [:index, :new, :create, :edit, :update, :destroy]
    patch "/membership/:id/reactivate/", to: "memberships#reactivate", as: "membership_reactivate"

    # league::games
    resources :games, only: [:new, :create]
  end

  # games
  resources :games, only: [:show]
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :memberships do
    def member
      where("memberships.role = ?", 0)
    end

    def admin
      where("memberships.role = ?", 1)
    end
  end

  has_many :leagues, through: :memberships do
    def member
      where("memberships.role = ?", 0)
    end

    def admin
      where("memberships.role = ?", 1)
    end
  end

  def is_admin_for?(other_user)
    (memberships.admin.pluck(:league_id) & other_user.memberships.pluck(:league_id)).any?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:show]
  before_action :redirect_user, only: [:new, :create, :reset]

  def show
    @leagues = current_user.leagues
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "signed up!"
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      flash[:alert] = "something went wrong"
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      flash[:alert] = "Something went wrong"
      redirect_to sign_up_path
    end
  end

  def reset
    redirect_to sign_in_path unless params[:token]
    @user = GlobalID::Locator.locate_signed(params[:token], for: request_path)
    redirect_to sign_up_path unless @user
  end

  def send_reset
    UserMailer.forgot_password(params[:email]).deliver_now
    redirect_to reset_sent_path
  end

  def assign_email
    @user = User.find(params[:id]).decorate
    @return_to = URI(request.referrer).path || dashboard_path
    authorize @user
  end

  def set_email
    @user = User.find(params[:id])
    authorize @user
    @user.update(user_params)
    if params[:notify]
      membership = Membership.find(params[:membership_id])
      UserMailer.welcome(membership).deliver_now
    end
    flash[:notice] = "Email set for #{@user.decorate.full_name}"
    redirect_to params[:return_to] || dashboard_path
  end

  private

  def impersonating?
    params[:impersonating] == "true"
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def request_path
    return "membership_invite" if request.original_fullpath.starts_with?("/invite/")
    "reset" if request.original_fullpath.starts_with?("/reset/")
  end
end

app/views/users/_league.html.erb
<li><%= link_to league.name, league_path(league) %></li>

app/views/users/assign_email.html.erb
<h1>Assign Email Address for <%= @user.full_name %></h1>

<%= form_with model: @user, url: set_email_path do |f| %>
  <%= hidden_field_tag :return_to, @return_to %>
  <%= hidden_field_tag :membership_id, params[:membership_id] %>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= label_tag do %>
      <%= check_box_tag :notify %>
      Notify user
    <% end %>
  </div>
  <%= f.submit %>
<% end %>

app/views/users/forgot.html.erb
<h2>Reset your password</h2>

<%= form_with url: send_reset_path do |f| %>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <%= f.submit "Reset your password" %>
<% end %>

<%= link_to "Or go back and sign in", sign_in_path %>

app/views/users/new.html.erb
<%= form_with model: @user, url: sign_up_path do |f| %>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit "Sign Up"%>
<% end %>

app/views/users/reset.html.erb
<h2>Set your password</h2>

<div>
  <%= form_with model: @user do |f| %>
    <p>Email Address: <%= @user.email %></p>
    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.submit "Set Password" %>
    </div>
  <% end %>
</div>

app/views/users/reset_sent.html.erb
<p>
  If your email exists in our database, we will send instructions to reset your password.
</p>

app/views/users/show.html.erb
<h1>Dashboard</h1>

<%= link_to "Create new league", new_league_path %>

Welcome <%= current_user.email %>!

<h2>Admin Leagues</h2>
<ul>
  <%= render partial: "league", collection: current_user.leagues.admin %>
</ul>

<h2>Member Leagues</h2>
<ul>
  <%= render partial: "league", collection: current_user.leagues.member %>
</ul>